/**
 * A PATH directory of fake backends for the binary smoke suite.
 *
 * Each stub is a `/bin/sh` script that replays one recording per exact argv,
 * the same shape `FixtureExecRunner` replays in-process, so the e2e suite and
 * the plugin suites share `test/fixtures/recordings/*.json` as their one source
 * of canned backend output. An argv with no recording exits 99 and names
 * itself on stderr, and every call is appended to a log the test reads back,
 * so a binary that never reached the stub, or reached it with the wrong
 * arguments, fails loudly rather than passing on empty output.
 *
 * Test-support only: nothing under `src/` imports this, and the smoke suite
 * deliberately avoids importing `src/` at runtime so it observes the packaged
 * artifact alone. The one `src/` import below is type-only and erased.
 */

import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { FixtureEntry } from '../../src/exec/fixtures';

/** One recorded backend call: an entry in `test/fixtures/recordings/*.json`, the shape `FixtureExecRunner` replays. */
export type Recording = FixtureEntry;

/** A written stub directory: what to put on PATH, and how to see what was called. */
export interface StubPath {
  /** The directory holding one executable per recorded `cmd`. */
  readonly bin: string;
  /** Every call so far, in order, as `<cmd> <args joined by space>`. */
  calls(): string[];
  /** The subset of {@link calls} that had no recording and so exited 99. */
  misses(): string[];
}

/** Parse one recording file. */
export function readRecording(path: string): Recording[] {
  return JSON.parse(readFileSync(path, 'utf8')) as Recording[];
}

interface Logs {
  readonly calls: string;
  readonly misses: string;
}

function lines(path: string): string[] {
  return existsSync(path) ? readFileSync(path, 'utf8').split('\n').filter(Boolean) : [];
}

/** Wrap a string in single quotes for `/bin/sh`, escaping any it contains. */
function shQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function script(cmd: string, entries: readonly Recording[], logs: Logs): string {
  const cases = entries.map((e) => {
    const body = [`    printf '%s' ${shQuote(e.result.stdout)}`];
    if (e.result.stderr) body.push(`    printf '%s' ${shQuote(e.result.stderr)} >&2`);
    body.push(`    exit ${e.result.exitCode}`);
    return `  ${shQuote(e.args.join(' '))})\n${body.join('\n')}\n    ;;`;
  });
  return [
    '#!/bin/sh',
    '# Generated by test/e2e/stub-path.ts from test/fixtures/recordings; not hand-edited.',
    `printf '%s %s\\n' ${shQuote(cmd)} "$*" >> ${shQuote(logs.calls)}`,
    'case "$*" in',
    ...cases,
    '  *)',
    `    printf '%s %s\\n' ${shQuote(cmd)} "$*" >> ${shQuote(logs.misses)}`,
    `    printf 'stub %s: no recording for argv: %s\\n' ${shQuote(cmd)} "$*" >&2`,
    '    exit 99',
    '    ;;',
    'esac',
    '',
  ].join('\n');
}

/**
 * Write one stub executable per distinct `cmd` into `<dir>/bin`, replaying
 * `recordings` by exact argv. Where two recordings share a cmd and argv the
 * first wins, so callers control precedence by order.
 *
 * @throws Error when a recorded arg contains a space: the scripts match on
 * `"$*"`, which joins args with spaces, so such an argv could not be told apart
 * from its split form.
 */
export function writeStubPath(dir: string, recordings: readonly Recording[]): StubPath {
  const bin = join(dir, 'bin');
  const logs: Logs = { calls: join(dir, 'calls.log'), misses: join(dir, 'misses.log') };
  mkdirSync(bin, { recursive: true });

  const byCmd = new Map<string, Recording[]>();
  const seen = new Set<string>();
  for (const r of recordings) {
    const spaced = r.args.find((a) => a.includes(' '));
    if (spaced !== undefined) {
      throw new Error(
        `stub-path: recorded arg ${JSON.stringify(spaced)} for ${r.cmd} contains a space, which "$*" matching cannot distinguish`,
      );
    }
    const key = `${r.cmd}\0${r.args.join('\0')}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const list = byCmd.get(r.cmd) ?? [];
    list.push(r);
    byCmd.set(r.cmd, list);
  }

  for (const [cmd, entries] of byCmd) {
    const path = join(bin, cmd);
    writeFileSync(path, script(cmd, entries, logs), 'utf8');
    chmodSync(path, 0o755);
  }

  return { bin, calls: () => lines(logs.calls), misses: () => lines(logs.misses) };
}
